name: Build LaTeX document
on: [push]
jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v1
            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@master
              with:
                  root_file: thesis.tex
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                branch: gh-pages
                folder: .